config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :orders
  resources :itemcarts do
    member do
      get :orders, to: 'orders#create'
      get :remove_item, to: 'itemcarts#destroy'
    end
  end
  devise_for :merchants
  resources :idproofs
  resources :merchants
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "merchants#index"

  # delete '/productimages/remove_image/:id' => 'productimages#remove_image', as: :remove_image

  # root "idproofs#index"
  root "products#index"

  resources :products do
  member do 
    get :wishlists, to: 'wishlists#create'
    get :itemcarts, to: 'itemcarts#cart'
  end
    resources :productimages
  end 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorie.rb
class Categorie < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :name, presence: true
end

app/models/idproof.rb
class Idproof < ApplicationRecord
  belongs_to :merchant
  mount_uploader :document, DocumentUploader
  validates :document ,presence: true
  # enum :status, { pending: 2, accept: 1,reject: 0},_default: :pending
  # enum :status, { pending: 0, accept: 1},_default: :pending
end

app/models/itemcart.rb
class Itemcart < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_one :idproof ,dependent: :destroy
  
  validates :email ,presence: true 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :merchant
  belongs_to :product
  belongs_to :itemcart
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categorie
  has_many :productimage,dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name,:price ,presence: true
  # enum :status, { active: 1, draft: 2, inactive: 0},_default: :draft
end

app/models/productimage.rb
class Productimage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
  validates :image,presence: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/controllers/idproofs_controller.rb
class IdproofsController < ApplicationController
  def index
    @idproofs = Idproof.all
  end
  def new
    @idproof = Idproof.new
  end
  def show
    @idproof = Idproof.find(params[:id])
  end
  def create
    @idproof.merchant_id = current_merchant.id 
    @idproof = Idproof.new(idproof_params)
    if @idproof.save
      redirect_to @idproof
    else
      render :new
    end
  end
  def destroy
    @idproof = Idproof.find(params[:id])
    @idproof.destroy

    redirect_to root_path
  end
  def update

  end
  def edit

  end
  private

  def idproof_params
    params.require(:idproof).permit(:name, :document, :status)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all
  end

  def show 
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(product_id: Itemcart.find(params[:id])
    .product.id, merchant_id: current_merchant.id, itemcart_id: params[:id], status:"pending")
    if @order.save
      redirect_to orders_path, notice: "Order placed successfully"
    else
      render :new
    end
  end
  private

    def order_params
      params.require(:order).permit(:status, :merchant_id, :product_id, :itemcart_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    # @products = Product.where(merchant_id: current_merchant.id)
  end 
  def new
    @product = Product.new
  end
  def show
    @product = Product.find(params[:id])
  end
  def create
    # debugger
    @product = Product.new(product_params)
    @product.merchant_id = current_merchant.id
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to @product
  end
  private

    def product_params
      params.require(:product).permit( :name, :price, :status, :categorie_id,:merchant_id ,:image, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/idproofs_helper.rb
module IdproofsHelper
end

app/helpers/itemcarts_helper.rb
module ItemcartsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/productimages_helper.rb
module ProductimagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/productsactives_helper.rb
module ProductsactivesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/idproofs/_form.html.erb
<%= form_with(model: idproof) do |form| %>
  <% if idproof.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idproof.errors.count, "error") %> prohibited this idproof from being saved:</h2>

      <ul>
        <% idproof.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# <div>
    <%#= form.label :merchant_id, style: "display: block" %>
    <%#= form.collection_select :merchant_id, Merchant.all, :id, :email %> 
  <%# </div> %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :document, style: "display: block" %>
    <%= form.file_field :document %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%#= form.text_field :status %>
    <%= form.select :status, [['pending', 'pending'], ['accept', 'accept'], ['reject', 'reject']] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/idproofs/_idproof.html.erb
<div id="<%= dom_id idproof %>">
  <p>
    <strong>Name:</strong>
    <%= idproof.name %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= idproof.document %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= idproof.status %>
  </p>

  <p>
    <strong>Merchant:</strong>
    <%= idproof.merchant_id %>
  </p> 

</div>

app/views/idproofs/edit.html.erb
<h1>Editing idproof</h1>

<%= render "form", idproof: @idproof %>

<br>

<div>
  <%= link_to "Show this idproof", @idproof %> |
  <%= link_to "Back to idproofs", idproofs_path %>
</div>

app/views/idproofs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Idproofs</h1>

<div id="idproofs">
  <% @idproofs.each do |idproof| %>
    <%#= render idproof %>
    <p>
      <%#= link_to "Show this idproof", idproof %>
      <%= link_to idproof.name, idproof %>
    </p>
  <% end %>
</div>

<%= link_to "New idproof", new_idproof_path %>

app/views/idproofs/new.html.erb
<h1>New idproof</h1>

<%= render "form", idproof: @idproof %>

<br>

<div>
  <%= link_to "Back to idproofs", idproofs_path %>
</div>

app/views/idproofs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @idproof %>

<div>
  <%= link_to "Edit this idproof", edit_idproof_path(@idproof) %> |
  <%= link_to "Back to idproofs", idproofs_path %>

  <%= button_to "Destroy this idproof", @idproof, method: :delete, data:{turbo_confirm: "Are you sure?"} %>
 
</div>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :merchant_id, style: "display: block" %>
    <%= form.text_field :merchant_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :itemcart_id, style: "display: block" %>
    <%= form.text_field :itemcart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>Merchant:</strong>
    <%= order.merchant_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= order.product_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= order.itemcart_id %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
 
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name  %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <table>
      <tr>
        <%= form.label :status, style: "display: block" %> &nbsp <%= form.label :categorie_id, style: "display: block" %>
        <%#= form.text_field :status %>
        <%= form.select :status, [['Active', 'Active'], ['Inactive', 'Inactive'], ['Draft', 'Draft']] %>
        <%#= select_tag(:active, options_for_select([['Active', true], ['Inactive', false], ['Draft', '']], params[:status]), :prompt => 'Status') %>
        &nbsp
        <%= form.collection_select :categorie_id, Categorie.all, :id, :name %>  
      </tr>
    </table>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  
  <%# <div> %>
    <%#= form.label :merchant_id, style: "display: block" %>
    <%#= form.collection_select :merchant_id, Merchant.all, :id, :email %> 
  <%# </div>  %>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  
  <p>
    <strong>Merchant:</strong>
    <%= Merchant.find(product.merchant_id).email %>
  </p> 
  
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= product.status %>
  </p>

  <p>
    <strong>Categorie:</strong>
    <%= product.categorie_id %>
    <%= product.categorie.name %>
  </p>

    
  <p> 
    <strong>Description:</strong>
    <%= product.description %>
  </p>
  
  <%= render 'productimages/form' %>

  <p>
    <strong>Image:</strong>
    <img src="<%= product.image %>" style = "width:10% ">
  </p>

  
</div>

app/views/products/_shopping.html.erb
<div class="container">
    <h3 class="h3">Shopping</h3>
        <div class="row ">
        <% @products.each do |p| %>
            <div class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#">
                            <img class="pic-1" src="<%= p.productimage.first.image if p.productimage.any? %>">
                            <img class="pic-2" src="<%= Productimage.first.image %>"> 
                            <%# <img class="pic-2" src="<%= Product.first.productimage.third.image %>
                        </a>
                        <ul class="social">
                            <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                            <li><a href="/products/<%= p.id %>/wishlists" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                            <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                        <span class="product-new-label">Sale</span>
                        <span class="product-discount-label">20%</span>
                    </div>
                    <ul class="rating">
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star disable"></li>
                    </ul>
                    <div class="product-content">
                        <h3 class="title"><a href="/products/<%= p.id %>"><%= p.name %></a></h3>
                        <div class="price"><%= p.price %></div>
                        <div><span><%= p.description %></span>
                        </div>
                        <div><%= p.status %></div>
                        <a class="add-to-cart" href="<%= itemcarts_product_path(p.id) %>">+ Add To Cart</a>
                    </div>
                </div>
            </div>
            <%# <div class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#">
                            <img class="pic-1" src="https://www.w3schools.com/bootstrap4/img_avatar4.png">
                            <img class="pic-2" src="https://www.w3schools.com/bootstrap4/img_avatar3.png">
                        </a>
                        <ul class="social">
                            <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                            <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                            <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                        <span class="product-new-label">Sale</span>
                        <span class="product-discount-label">50%</span>
                    </div>
                    <ul class="rating">
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                    </ul>
                    <div class="product-content">
                        <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                        <div class="price">$5.00
                            <span>$10.00</span>
                        </div>
                        <a class="add-to-cart" href="">+ Add To Cart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#">
                            <img class="pic-1" src="https://www.w3schools.com/bootstrap4/img_avatar4.png">
                            <img class="pic-2" src="https://www.w3schools.com/bootstrap4/img_avatar3.png">
                        </a>
                        <ul class="social">
                            <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                            <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                            <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                        <span class="product-new-label">Sale</span>
                        <span class="product-discount-label">50%</span>
                    </div>
                    <ul class="rating">
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                    </ul>
                    <div class="product-content">
                        <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                        <div class="price">$5.00
                            <span>$10.00</span>
                        </div>
                        <a class="add-to-cart" href="">+ Add To Cart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#">
                            <img class="pic-1" src="https://www.w3schools.com/bootstrap4/img_avatar4.png">
                            <img class="pic-2" src="https://www.w3schools.com/bootstrap4/img_avatar3.png">
                        </a>
                        <ul class="social">
                            <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                            <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                            <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                        <span class="product-new-label">Sale</span>
                        <span class="product-discount-label">50%</span>
                    </div>
                    <ul class="rating">
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                    </ul>
                    <div class="product-content">
                        <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                        <div class="price">$5.00
                            <span>$10.00</span>
                        </div>
                        <a class="add-to-cart" href="">+ Add To Cart</a>
                    </div>
                </div>
            </div> %>
        <% end %>
    </div>
</div>
<hr>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

<!--Shopping-->
<% @products.each_slice(3).each do |p| %>
  <%= render 'shopping',shopping: p %>
<% end %>
<!--End of Shopping-->

<div id="products">
  <% @products.each do |product| %>
    <%#= render product %>
    <p>
      <%#= link_to "Show this product", product %>
      <%#= link_to product.name, product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

</html>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>
<%= render @product.productimage %>

<div>
  
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>