config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :orders
  resources :itemcarts do
    member do
      get :orders, to: 'orders#create'
      get :remove_item, to: 'itemcarts#destroy'
    end
  end
  devise_for :merchants
  resources :idproofs
  resources :merchants
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "merchants#index"

  # delete '/productimages/remove_image/:id' => 'productimages#remove_image', as: :remove_image

  # root "idproofs#index"
  root "products#index"

  resources :products do
  member do 
    get :wishlists, to: 'wishlists#create'
    get :itemcarts, to: 'itemcarts#cart'
  end
    resources :productimages
  end 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorie.rb
class Categorie < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :name, presence: true
end

app/models/idproof.rb
class Idproof < ApplicationRecord
  belongs_to :merchant
  mount_uploader :document, DocumentUploader
  validates :document ,presence: true
  # enum :status, { pending: 2, accept: 1,reject: 0},_default: :pending
  # enum :status, { pending: 0, accept: 1},_default: :pending
end

app/models/itemcart.rb
class Itemcart < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_one :idproof ,dependent: :destroy
  
  validates :email ,presence: true 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :merchant
  belongs_to :product
  belongs_to :itemcart
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categorie
  has_many :productimage,dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name,:price ,presence: true
  # enum :status, { active: 1, draft: 2, inactive: 0},_default: :draft
end

app/models/productimage.rb
class Productimage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
  validates :image,presence: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/controllers/idproofs_controller.rb
class IdproofsController < ApplicationController
  def index
    @idproofs = Idproof.all
  end
  def new
    @idproof = Idproof.new
  end
  def show
    @idproof = Idproof.find(params[:id])
  end
  def create
    @idproof.merchant_id = current_merchant.id 
    @idproof = Idproof.new(idproof_params)
    if @idproof.save
      redirect_to @idproof
    else
      render :new
    end
  end
  def destroy
    @idproof = Idproof.find(params[:id])
    @idproof.destroy

    redirect_to root_path
  end
  def update

  end
  def edit

  end
  private

  def idproof_params
    params.require(:idproof).permit(:name, :document, :status)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all
  end

  def show 
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(product_id: Itemcart.find(params[:id])
    .product.id, merchant_id: current_merchant.id, itemcart_id: params[:id], status:"pending")
    if @order.save
      redirect_to orders_path, notice: "Order placed successfully"
    else
      render :new
    end
  end
  private

    def order_params
      params.require(:order).permit(:status, :merchant_id, :product_id, :itemcart_id)
    end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def index
    @wishlists = Wishlist.all
  end

  def show
    @wishlist = Wishlist.find(params[:id])
  end

  def new
    @wishlist = Wishlist.new
  end

  def create 
    @wishlist = Wishlist.new(product_id: params[:id],merchant_id: current_merchant.id)
    if @wishlist.save
      redirect_to wishlists_path, notice: "Added to wishlist"
    end
  end

  private

    def wishlist_params
      params.require(:wishlist).permit(:product_id, :merchant_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/idproofs_helper.rb
module IdproofsHelper
end

app/helpers/itemcarts_helper.rb
module ItemcartsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/productimages_helper.rb
module ProductimagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/productsactives_helper.rb
module ProductsactivesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_wish.html.erb
<div class="container wrapper">
  <div class="row cart-body">
    <form class="form-horizontal" method="post" action="">
      <div
        class=""
      >
        <!--REVIEW ORDER-->
        <div class="panel panel-info">
          <div class="panel-heading">
            Review Order
          </div>
          <div class="panel-body">
          <% @wishlists.each do |w| %>
            <div class="form-group">
              <div class="col-sm-3 col-xs-3">
                <img
                  class="img-responsive"
                  src="<%= w.product.image %>"
                />
              </div>
              <div class="col-sm-6 col-xs-6">
                <div class="col-xs-12"><a href=""><%= w&.product&.name %></div>
                <div class="col-xs-12">
                  <%# <small>Quantity:<span></span></small> %>
                  <%# <small>Size:<span></span></small> %>
                </div>
              </div>
              <div class="col-sm-3 col-xs-3 text-right">
                <h6><span>$</span><%= w&.product&.price %></h6>
              <p><%= link_to "Remove",remove_item_itemcart_path(w) %></p>
              <p><%#= link_to "Remove","/products/#{i.product_id}/itemcarts", method: :delete %></p>
              <p><%#= link_to "Remove", @itemcart, method: :delete %></p>
              <p><%= link_to "Order",orders_itemcart_path(w) %></p>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
​

app/views/wishlists/_wishlist.html.erb
<div id="<%= dom_id wishlist %>">
  <p>
    <strong>Product:</strong>
    <%= wishlist.product_id %>
  </p>

  <p>
    <strong>Merchant:</strong>
    <%= wishlist.merchant_id %>
  </p>

</div>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render "form", wishlist: @wishlist %>

<br>

<div>
  <%= link_to "Show this wishlist", @wishlist %> |
  <%= link_to "Back to wishlists", wishlists_path %>
</div>

app/views/wishlists/index.html.erb
<link
  href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>


<%= render partial: 'wish' %>


<div id="wishlists">
  <% @wishlists.each do |wishlist| %>
    <%#= render wishlist %>
    <p>
      <%#= link_to "Show this wishlist", wishlist %>
    </p>
  <% end %>
</div>

<%#= link_to "New wishlist", new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<%= render "form", wishlist: @wishlist %>

<br>

<div>
  <%= link_to "Back to wishlists", wishlists_path %>
</div>

app/views/wishlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wishlist %>

<div>
  <%= link_to "Edit this wishlist", edit_wishlist_path(@wishlist) %> |
  <%= link_to "Back to wishlists", wishlists_path %>

  <%= button_to "Destroy this wishlist", @wishlist, method: :delete %>
</div>