config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :orders
  resources :itemcarts do
    member do
      get :orders, to: 'orders#create'
      get :remove_item, to: 'itemcarts#destroy'
    end
  end
  devise_for :merchants
  resources :idproofs
  resources :merchants
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "merchants#index"

  # delete '/productimages/remove_image/:id' => 'productimages#remove_image', as: :remove_image

  # root "idproofs#index"
  root "products#index"

  resources :products do
  member do 
    get :wishlists, to: 'wishlists#create'
    get :itemcarts, to: 'itemcarts#cart'
  end
    resources :productimages
  end 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorie.rb
class Categorie < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :name, presence: true
end

app/models/idproof.rb
class Idproof < ApplicationRecord
  belongs_to :merchant
  mount_uploader :document, DocumentUploader
  validates :document ,presence: true
  # enum :status, { pending: 2, accept: 1,reject: 0},_default: :pending
  # enum :status, { pending: 0, accept: 1},_default: :pending
end

app/models/itemcart.rb
class Itemcart < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_one :idproof ,dependent: :destroy
  
  validates :email ,presence: true 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :merchant
  belongs_to :product
  belongs_to :itemcart
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categorie
  has_many :productimage,dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name,:price ,presence: true
  # enum :status, { active: 1, draft: 2, inactive: 0},_default: :draft
end

app/models/productimage.rb
class Productimage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
  validates :image,presence: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/controllers/idproofs_controller.rb
class IdproofsController < ApplicationController
  def index
    @idproofs = Idproof.all
  end
  def new
    @idproof = Idproof.new
  end
  def show
    @idproof = Idproof.find(params[:id])
  end
  def create
    @idproof.merchant_id = current_merchant.id 
    @idproof = Idproof.new(idproof_params)
    if @idproof.save
      redirect_to @idproof
    else
      render :new
    end
  end
  def destroy
    @idproof = Idproof.find(params[:id])
    @idproof.destroy

    redirect_to root_path
  end
  def update

  end
  def edit

  end
  private

  def idproof_params
    params.require(:idproof).permit(:name, :document, :status)
  end

end

app/controllers/itemcarts_controller.rb
class ItemcartsController < ApplicationController
  def index
    @itemcarts = Itemcart.all
  end

  def create
    @itemcart = Itemcart.new(itemcart_params)
    @itemcart.merchant_id = current_merchant.id
    @itemcart.product_id = params[:product_id]
    if @itemcart.save
      redirect_to @itemcart ,notice: "items successfully added to cart"
    else
      render :new
    end
  end

  def new
    @itemcart = Itemcart.new
  end

  def show
    @itemcart = Itemcart.find(params[:id])
  end

  def cart
    @cart = Itemcart.new(product_id: params[:id],merchant_id: current_merchant.id,qnty:1,size:"XS")
    @cart.save!
    redirect_to products_path,notice:"Successfully added to cart"
  end

  # def total 
  #   @price = 
  # end
  def destroy
    @itemcart = Itemcart.find(params[:id])
    @itemcart.destroy
    redirect_to itemcarts_path,notice: "Removed successfully"
  end
  private

    def itemcart_params
      params.require(:itemcart).permit(:qnty, :size, :product_id, :merchant_id)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all
  end

  def show 
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(product_id: Itemcart.find(params[:id])
    .product.id, merchant_id: current_merchant.id, itemcart_id: params[:id], status:"pending")
    if @order.save
      redirect_to orders_path, notice: "Order placed successfully"
    else
      render :new
    end
  end
  private

    def order_params
      params.require(:order).permit(:status, :merchant_id, :product_id, :itemcart_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/idproofs_helper.rb
module IdproofsHelper
end

app/helpers/itemcarts_helper.rb
module ItemcartsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/productimages_helper.rb
module ProductimagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/productsactives_helper.rb
module ProductsactivesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/itemcarts/_form.html.erb
<%= form_with(model: itemcart) do |form| %>
 
  <div>
    <%= form.label :qnty, style: "display: block" %>
    <%= form.number_field :qnty %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/itemcarts/_itemcart.html.erb
<div id="<%= dom_id itemcart %>">
  <p>
    <strong>Qnty:</strong>
    <%= itemcart.qnty %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= itemcart.size %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= itemcart.product_id %>
  </p>

  <p>
    <strong>Merchant:</strong>
    <%= Merchant.find(itemcart.merchant_id).email %>
  </p>
  
</div>

app/views/itemcarts/_review.html.erb
<div class="container wrapper">
  <div class="row cart-body">
    <form class="form-horizontal" method="post" action="">
      <div
        class=""
      >
        <!--REVIEW ORDER-->
        <div class="panel panel-info">
          <div class="panel-heading">
            Review Order
          </div>
          <div class="panel-body">
          <% @itemcarts.each do |i| %>
            <div class="form-group">
              <div class="col-sm-3 col-xs-3">
                <img
                  class="img-responsive"
                  src="<%= i.product.image %>"
                />
              </div>
              <div class="col-sm-6 col-xs-6">
                <div class="col-xs-12"><a href="itemcarts/<%= i.id %>"><%= i&.product&.name %></div>
                <div class="col-xs-12">
                  <small>Quantity:<span><%= i.qnty %></span></small>
                  <small>Size:<span><%= i.size %></span></small>
                </div>
              </div>
              <div class="col-sm-3 col-xs-3 text-right">
                <h6><span>$</span><%= i&.product&.price %></h6>
              <p><%= link_to "Remove",remove_item_itemcart_path(i) %></p>
              <p><%#= link_to "Remove","/products/#{i.product_id}/itemcarts", method: :delete %></p>
              <p><%#= link_to "Remove", @itemcart, method: :delete %></p>
              <p><%= link_to "Order",orders_itemcart_path(i) %></p>
              <p><%#= link_to "Wishlist", wishlists_product_path(i) %></p>
              <a href="/products/<%= i.product.id %>/wishlists">Wishlist</a>
              </div>
            </div>
            <% end %>
            <%# <div class="form-group"><hr /></div> %>
            <%# <div class="form-group">
              <div class="col-sm-3 col-xs-3">
                <img
                  class="img-responsive"
                  src="https://c1.staticflickr.com/1/466/19681864394_c332ae87df_t.jpg"
                />
              </div>
              <div class="col-sm-6 col-xs-6">
                <div class="col-xs-12">Product name</div>
                <div class="col-xs-12">
                  <small>Quantity:<span>1</span></small>
                </div>
              </div>
              <div class="col-sm-3 col-xs-3 text-right">
                <h6><span>$</span>25.00</h6>
              </div>
            </div> %>
            <%# <div class="form-group"><hr /></div> %>
            <%# <div class="form-group">
              <div class="col-sm-3 col-xs-3">
                <img
                  class="img-responsive"
                  src="https://c1.staticflickr.com/1/466/19681864394_c332ae87df_t.jpg"
                />
              </div>
              <div class="col-sm-6 col-xs-6">
                <div class="col-xs-12">Product name</div>
                <div class="col-xs-12">
                  <small>Quantity:<span>2</span></small>
                </div>
              </div>
              <div class="col-sm-3 col-xs-3 text-right">
                <h6><span>$</span>50.00</h6>
              </div>
            </div> %>
            <div class="form-group"><hr /></div>
            <div class="form-group">
              <div class="col-xs-12">
                <strong>Subtotal</strong>
                <div class="pull-right"><span>$</span><span>200.00</span></div>
              </div>
              <div class="col-xs-12">
                <small>Shipping</small>
                <div class="pull-right"><span>-</span></div>
              </div>
            </div>
            <div class="form-group"><hr /></div>
            <div class="form-group">
              <div class="col-xs-12">
                <strong>Order Total</strong>
                <div class="pull-right"><span>$</span><span>150.00</span></div>
              </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                  <div class="pull-right"><span></span><span><a class="btn-primary btn" href="">Checkout</a></span></div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
​

app/views/itemcarts/edit.html.erb
<h1>Editing itemcart</h1>

<%= render "form", itemcart: @itemcart %>

<br>

<div>
  <%= link_to "Show this itemcart", @itemcart %> |
  <%= link_to "Back to itemcarts", itemcarts_path %>
</div>

app/views/itemcarts/index.html.erb
<link
  href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<%= render partial:'review' %>



<p style="color: green"><%= notice %></p>



<div id="itemcarts">
  <% @itemcarts.each do |itemcart| %>
    <%#= render itemcart %>
    <p>
    <%#= link_to "Show this itemcart", itemcart %>
    </p>
  <% end %>
</div>

<%#= link_to "New itemcart", new_itemcart_path %>

app/views/itemcarts/new.html.erb
<h1>New itemcart</h1>

<%= render "form", itemcart: @itemcart %>

<br>

<div>
  <%= link_to "Back to itemcarts", itemcarts_path %>
</div>

app/views/itemcarts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @itemcart %>


<div>
  <%= link_to "Edit this itemcart", edit_itemcart_path(@itemcart) %> |
  <%= link_to "Back to itemcarts", itemcarts_path %>

  <%= button_to "Destroy this itemcart", @itemcart, method: :delete %>
</div>